apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: smartfalleh
data:
  # Configuration Base de Données
  DB_HOST: "mysql-service"  # Utilise le service Kubernetes au lieu de localhost
  DB_PORT: "3306"
  DB_USERNAME: "root"
  DB_DATABASE: "smartfallah"
  FRONT_URL: "http://smartfalleh.local"
  
  # Configuration Email (valeurs par défaut)
  EMAIL_USER: "ssmartfallah@gmail.com"
  USE_ETHEREAL: "false"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "ssmartfallah@gmail.com"
  SMTP_FROM: "SmartFalleh <ssmartfallah@gmail.com>"
  
  # Autres
  NODE_ENV: "production"
  PORT: "3000"